config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show] do
    resources :jobs, only:  [:new]
    # resources :bookings, only: [:edit, :update, :destroy]
  end
  resources :jobs, only: [:index, :create,:edit, :update, :show, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: [:edit, :update, :destroy]

  get 'owned_jobs', to: "dashboard_owned_jobs#index"
  get 'bookings', to: "bookings#index" # my bookings as a user / job researcher
  get 'requests', to: "bookings#requests" # my bookings as a job offerer
  post 'requests', to: "bookings#requests" # my bookings as a job offerer
  post 'approve', to: "bookings#approve"
  post 'decline', to: "bookings#decline"
  post 'bookings', to: "bookings#create"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :message, presence: true
end

app/models/job.rb
class Job < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one :review

  include PgSearch
  pg_search_scope :text_search,
  against: [ :title, :description, :location, :category ],
  using: {
    tsearch: { prefix: true }
  }

  validates :title, presence: true
  validates :category, presence: true, inclusion: {in: ["arts & design", "business & finance", "science", "academia", "sports & events", "services", "gastronomy", "entertainment", "transportation", "politics", "healthcare"]}
  validates :price, presence: true
  validates :date, presence: true

  def self.unbooked_or_bookable
    sql = <<-SQL
      SELECT DISTINCT jobs.id FROM jobs
      FULL JOIN bookings
      ON jobs.id = bookings.job_id
      WHERE bookings.job_id IS NULL
      OR bookings.status IN (0, 2);
    SQL
    ids = find_by_sql(sql).pluck(:id)
    where(id: ids)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :message, presence: true
  validates :title, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :rented_jobs, through: :bookings, source: :job # n : n relation
  has_many :owned_jobs, class_name: "Job"
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!, except: [:index]

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :requests], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, except: :requests, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    redirect_to(root_path)
    flash[:alert] = "You are not authorized to perform this action."
  end
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :photo, :email, :password, :current_password, :is_female, :date_of_birth) }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :set_user, only: [:new, :create, :index, :update, :requests]
before_action :set_job, only: [:new, :create]
before_action :set_booking, only: [ :update, :destroy ]


  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.job = @job
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def index
    @bookings = policy_scope(Booking).where(user_id: current_user.id)
    authorize @bookings
  end

  def requests
    @bookings = current_user.owned_jobs.map(&:bookings).flatten
  end

  # def edit
  #   authorize @booking
  # end

  def update
    @booking.update(booking_params)
    authorize @booking
    redirect_to requests_path
  end

  def destroy
    @booking.destroy
    authorize @booking
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:message, :status)
  end

  def set_user
    @user = current_user
  end

  def set_job
    @job = Job.find(params[:job_id])
  end

   def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/dashboard_owned_jobs_controller.rb
class DashboardOwnedJobsController < ApplicationController
  def index
    @jobs = policy_scope(Job).where(user_id: current_user.id)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index

    if params[:query].present? #all jobs displayed if searched with no input

      @jobs = policy_scope(Job).unbooked_or_bookable.text_search(params[:query])
      if params[:category].present?
        @jobs = @jobs.select{ |job| job.category == params[:category]  }
      end
      set_markers
    else
      @jobs = policy_scope(Job).unbooked_or_bookable
      if params[:category].present?
        @jobs = @jobs.select{ |job| job.category == params[:category]  }
      end
      set_markers
    end
  end

  def show
    authorize @job
    @booking = Booking.new
    authorize @booking
    @markers = [{
        lat: @job.latitude,
        lng: @job.longitude,
        infoWindow: { content: render_to_string(partial: "/shared/map_box", locals: { job: @job }) },
      }]
  end

  def new
    @job = Job.new
    authorize @job
  end

  def create
    @user = current_user
    @job = Job.new(job_params)
    @job.user = @user
    authorize @job
    if @job.valid?
      @job.save
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  def edit
    authorize @job
  end

  def update
    @job.update(job_params)
    authorize @job
    redirect_to job_path(@job)
  end

  def destroy
    @job.destroy
    authorize @job
    redirect_to root_path
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :category, :date, :price, :description, :guided, :photo, :location)
  end

  def set_markers
    @markers = @jobs.map do |job|
      {
        lat: job.latitude,
        lng: job.longitude,
        infoWindow: { content: render_to_string(partial: "/shared/map_box", locals: { job: job }) },
      }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_job, only: [:new, :create]
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @user = current_user
    @review = Review.new(review_params)
    authorize @review
    @review.user = @user
    @review.job = @job
    if @review.save!
      redirect_to user_path(@job.user)
    else
      render :new
    end
  end

  private

  def set_job
    @job = Job.find(params[:job_id])
  end

  def review_params
    params.require(:review).permit(:title, :message, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def show
    authorize @user
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% @title="My bookings" %>

<div class="container light-bkg">
  <% if @bookings.empty? %>
    <h2>No Bookings right now.</h2>
    <h2>Add a Job to get booked!</h2>
  <% else %>

    <h2>My job requests</h2>
    <% @bookings.each do |booking|  %>

      <div class="item">
        <%= cl_image_tag booking.job.photo, height: 100, width: 150, crop: :fill, class:"job-thumbnail" %>
        <div class="item-name text-left">
          <h4><strong>Posted by:</strong></h4>
          <p><%= booking.job.user.first_name.nil? ? booking.job.user.email : booking.job.user.first_name  %></p>
          <h4><strong>Happening on:</strong></h4>
          <p>(<%= booking.job.date %>)</p>
            </div>
        <div class="item-body">
          <h3><strong><%= link_to booking.job.title.upcase, job_path(booking.job) %></strong></h3>
          <p><strong>My message: </strong><%= booking.message %></p>
          <p>(requested: <%= booking.created_at.to_formatted_s(:short) %>)</p>
        </div>
        <div class="item-status">
          <% if booking.status == 2 %>
            <p class="status pending">Pending</p>
          <% elsif booking.status == 0 %>
            <p class="status declined">Declined</p>
          <% elsif booking.status == 1 %>
            <p class="status accepted">Accepted</p>
          <% end %>
          <p class="price">€<%= booking.job.price %></p>
        </div>
        <div class="item-action">
          <% if booking.status == 1 %>
            <%= link_to new_job_review_path(booking.job) do %>
            <div class="btn btn-success button-width btn-margin">
              Review
            </div>
            <% end %>
          <% end %>
          <%= link_to booking_path(booking), method: :delete, data: {confirm: "Are you sure?"} do %>
          <div class="btn btn-warning button-width btn-margin">
            Cancel
          </div>
          <% end %>
        </div>
      </div>

    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<% @title="Book the job!" %>

    <div class="container" style="margin-top: 100px;">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2><%= @job.title %></h2>
      <p>(<%= @job.date %>)</p>
      <br>
      <div class="job-book">
        <h4>Interested? Then say something, message can't be blank!</h4>
        <%= simple_form_for [@job, @booking],  method: :post do |f| %>
        <%= f.input :message, label: "Contact the job owner" %>
        <%= f.hidden_field :status, value: 2 %>
        <%= f.submit "Book the job now!", class: "btn btn-danger btn-job-book" %>
        <% end %>
        <div class="spacer">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/requests.html.erb
<% @title="Received requests" %>
<div class="container light-bkg">

<h2>Received applications</h2>

<% @bookings.each do |booking|  %>

  <div class="item">
    <%= cl_image_tag booking.job.photo, height: 100, width: 150, crop: :fill, class:"job-thumbnail" %>
    <div class="item-name text-left">
      <h3><strong><%= link_to booking.job.title.upcase, job_path(booking.job) %></strong></h3>
      <h4><strong>Happening on:</strong></h4>
      <p>(<%= booking.job.date %>)</p>
        </div>
    <div class="item-body">
      <div class="message">
        <%= cl_image_tag booking.user.photo, class: "avatar-large" %>
        <div class="message-body">
          <p><strong>Requested by: </strong><%= booking.user.first_name.nil? ? booking.user.email : booking.user.first_name  %></p>
          <p><strong>Message: </strong><%= booking.message %></p>
          <p>(requested: <%= booking.created_at.to_formatted_s(:short) %>)</p>
        </div>
      </div>
    </div>
    <div class="item-status">
      <% if booking.status == 2 %>
        <p class="status pending">Pending</p>
      <% elsif booking.status == 0 %>
        <p class="status declined">Declined</p>
      <% elsif booking.status == 1 %>
        <p class="status accepted">Accepted</p>
      <% end %>
      <p class="price">€<%= booking.job.price %></p>
    </div>
    <div class="item-action">
      <p>
        <% job = booking.job %>
        <%= form_for booking,  method: :patch do |f| %>
          <%= f.hidden_field :status, :value => 1 %>
          <%= f.submit "Approve", class: "btn btn-success button-width" %>
        <% end %>
      </p>
      <p>
       <%= form_for booking, method: :patch do |f| %>
        <%= f.hidden_field :status, :value => 0 %>
        <%= f.submit "Decline", class: "btn btn-danger button-width" %>
      </p>
      <% end %>
    </div>
  </div>

<% end %>
</div>

app/views/dashboard_owned_jobs/index.html.erb
<% @title="Posted jobs" %>


<div class="container light-bkg">
  <% if @jobs.empty? %>
    <h2>No Jobs right now.</h2>
    <h2>Add a Job to get booked!</h2>
  <% else %>
  <h2>My jobs</h2>

    <% @jobs.each do |job| %>
      <div class="item">
        <%= cl_image_tag job.photo, height: 100, width: 150, crop: :fill, class:"job-thumbnail" %>
        <div class="item-name text-left">
          <h4><strong>Posted on:</strong></h4>
          <p><%= job.created_at.to_formatted_s(:short)  %></p>
          <h4><strong>Happening on:</strong></h4>
          <p>(<%= job.date %>)</p>
            </div>
        <div class="item-body">
          <h3><strong><%= link_to job.title.upcase, job_path(job) %></strong></h3>
          <p><strong>Location: </strong><%= job.location %></p>
        </div>
        <div class="item-status">
          <p class="price">€<%= job.price %></p>
        </div>
        <div class="item-action">
          <%= link_to edit_job_path(job) do %>
            <div class="btn btn-success button-width btn-margin">
              Edit
            </div>
          <% end %>
          <%= link_to job_path(job), method: :delete, data: {confirm: "Are you sure?"} do %>
            <div class="btn btn-danger button-width btn-margin">
              Delete
            </div>
          <% end %>
        </div>
      </div>

    <% end %>
  <% end %>
</div>

app/views/jobs/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= simple_form_for job do |f| %>
    <%= f.input :title %>
    <%= f.input :category, collection: ["arts & design", "business & finance", "science", "academia", "sports & events", "services", "gastronomy", "entertainment", "transportation", "politics", "healthcare"] %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :guided, input_html: {value: :guided} %>
    <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
      <div class="button-center">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>
<div class="spacer"></div>

app/views/jobs/edit.html.erb
<% @title="Edit your job" %>
<br><br>

<div class="container">
  <h1>Edit your Job</h1>
  <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= form_tag(jobs_path, method: :get) do %>
        <div class="form-inline flex-form searchbox" style="margin-top: 5vh;">
          <%= text_field_tag :query, params[:query], placeholder: params[:query], class:"form-control input-field flex-stretch" %>
          <%= select_tag :category, options_for_select([["all categories", ""],
            ["arts & design", "arts & design"],
            ["business & finance", "business & finance"],
            ["politics", "politics"],
            ["academia", "academia"],
            ["science", "science"],
            ["sports & events","sports & events"],
            ["services","services"],
            ["gastronomy", "gastronomy"],
            ["entertainment","entertainment"],
            [ "transportation","transportation"],
            [ "healthcare", "healthcare"]
            ]), class: "form-control input-field" %>
          <%= submit_tag 'Search', name: nil, class:"btn btn-primary search-button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="card-overview-header" >
  <h1 style="font-size: 30px">Your Search Results (<%= @jobs.uniq.count %>)</h1>
</div>

<div class="main-container-index">
  <div class="card-container">
    <div class="row">
      <% @jobs.uniq.each do |job| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
          <div class="card">
            <%= link_to job_path(job) do %>
              <% url = job.photo.nil? ? image_path('http://via.placeholder.com/250x350', width: 400, height: 250, crop: :fill) : cl_image_path(job.photo, width: 400, height: 250, crop: :fill) %>
              <div class="card-header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url %>')"></div>
              <div class="card-footer">
                <div class="card-description" style=" color:black;">
                 <h2 style="padding-left: 6px;"> <%= job.title %></h2>
                  <table>
                    <tr>
                      <td> <p> <i class="fas fa-briefcase"></i> </p> </td>
                      <td> <p> <%= job[:category] %> </p> </td>
                    </tr>
                    <tr>
                      <td> <p> <i class="fas fa-map-marker-alt"></i> </p> </td>
                      <td> <p> <%= job[:location] %> </p> </td>
                    </tr>
                    <tr>
                      <td> <p> <i class="fab fa-bitcoin"></i> </p> </td>
                      <td> <p> <%= job[:price] %> </p> </td>
                    </tr>
                    <tr>
                      <td> <p> <i class="fas fa-calendar-alt"></i> </p> </td>
                      <td> <p> <%= job[:date] %> </p> </td>
                    </tr>
                  </table>
                </div>

              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

    <div
      id="map" class="hidden-xs"
      data-markers="<%= @markers.to_json %>"
    ></div>
  </div>
</div>

<script>
    ScrollReveal().reveal('.card', { delay: 300, origin: 'bottom', distance: '50px' });
</script>

app/views/jobs/new.html.erb
<% @title="Create new job!" %>

<div class="container">
  <h1 class="centered-title">Create a new Job</h1>
  <%= render 'form', job: @job %>
</div>

app/views/jobs/show.html.erb
<% @title="Details" %>
<% url = @job.photo.blank? ? image_path('http://via.placeholder.com/500x920', height: 500, width: 920) : cl_image_path(@job.photo, height: 500, width: 920, crop: :fit) %>
<div class="banner" id="job-pic" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url %>');">
  <div class="container vhheight">
    <div class="relative">
      <a href="#book">
      <div class="btn btn-lg btn-danger booking-call hidden-xs hidden-sm"> BOOK NOW</div></a>
      <div class="headbox headbox-job-title">
        <h1><%= @job.title %></h1>
      <h3><i class="fas fa-map-marker-alt"></i><%= @job.location %></h3>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="mini-info">
        <div class="col-xs-12 col-md-3">
          <div class="job-owner">
          <%= cl_image_tag @job.user.photo, class: "avatar-large" %>
            <p class="job-owner-name"><%= @job.user.first_name %></p>
          </div>
        </div>
        <div class="col-xs-12 col-md-3">
          <p><i class="fas fa-calendar-alt"></i><%= @job.date %></p>
        </div>
        <div class="col-xs-12 col-md-3">
          <p><i class="fas fa-briefcase"></i><%= @job.category %></p>
        </div>
        <div class="col-xs-12 col-md-3">
          <p><i class="fas fa-hands-helping"></i>
            <%= @job.guided? ? "with guide" : "without guide" %>
          </p>
        </div>
        <div class="col-xs-12 col-md-3">
          <p><i class="fab fa-bitcoin"></i><%= @job.price %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="job-description">
        <h3>Details</h3>
        <p><%= @job.description %></p>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div id="map" data-markers="<%= @markers.to_json %>" style="height: 300px; margin-top: 0; border-radius: 3px; box-shadow: 1px 1px 1px rgba(1, 1, 1, 0.2);"></div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="job-book" id="book">
        <h4>Interested?</h4>
            <%= simple_form_for [@job, @booking],  method: :post do |f| %>
            <%= f.input :message, label: "Contact the job owner" %>
            <%= f.hidden_field :status, value: 2 %>
            <%= f.submit "Book the job now!", class: "btn btn-danger btn-job-book" %>
          <% end %>
        <div class="spacer"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @title.nil? ? "Do my job" : @title  %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://3.bp.blogspot.com/-eoATvZkAiAg/VZaqEI1nLzI/AAAAAAAACXg/140hoGl5Sw8/s1600/confused%2B%25281%2529.jpg');">
  <div class="container">
    <div class="row">
      <div class="call-to-action text-center hidden-xs hidden-sm">
        <h1>Try any job you'd like!</h1>

        <h2>Step in the shoes of a <strong id="banner-typed-text"></strong> for one day.</h2>
      </div>
      <div class="call-to-action text-center hidden-md hidden-lg">
        <h1 style="font-size: 36px; margin-top: 50px;">Try any job you'd like!</h1>
        <h2>Step in the shoes of a pilot, a therapist or a clown for one day.</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-8 col-xs-offset-2 col-md-8 col-md-offset-2">
        <%= form_tag(jobs_path, method: :get) do %>
          <div class="form-inline flex-form searchbox">
            <%= text_field_tag :query, params[:query], placeholder: "What job are you looking for?", class:"form-control flex-stretch input-field" %>
            <%= submit_tag 'Search', name: nil, class:"btn search-button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>




<%= render 'shared/addinfo' %>
<%= render 'shared/team' %>

<script>
    ScrollReveal().reveal('.add-info', { delay: 600, origin: 'bottom', distance: '50px', easing: 'ease-in' });
    ScrollReveal().reveal('.add-info2', { delay: 900, origin: 'bottom', distance: '50px', easing: 'ease-in' });
    ScrollReveal().reveal('.add-info3', { delay: 1200, origin: 'bottom', distance: '50px', easing: 'ease-in' });
    ScrollReveal().reveal('.add-info4', { delay: 1500, origin: 'bottom', distance: '50px', easing: 'ease-in' });
</script>

app/views/shared/_flashes.html.erb
<div style="margin-top:70px;">
  <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
</div>

app/views/shared/_map_box.html.erb
<div class="info-window">
  <p><strong><%= job.title %></strong></p>
  <p><%= job.location %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "hatlogo.png", height: 50 %>
  <h4 class="projectname">Do-My-Job</h3>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <%= link_to "Create new job", new_user_job_path(current_user.id), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My jobs", owned_jobs_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Received applications", requests_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My job requests", bookings_path, class: "navbar-wagon-item navbar-wagon-link navbar-divider" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->


  <div class="navbar-wagon-item hidden-md hidden-lg">
      <% if user_signed_in? %>

    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Create new job", new_user_job_path(current_user.id) %></li>
        <li><%= link_to "My jobs", owned_jobs_path %></li>
        <li><%= link_to "Received applications", requests_path %></li>
        <li><%= link_to "My job requests", bookings_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
     <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  </div>
</div>